export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_VIEWING_INGREDIENT = 'ADD_VIEWING_INGREDIENT';
export const REMOVE_VIEWING_INGREDIENT = 'REMOVE_VIEWING_INGREDIENT';
export const SET_BUN = 'SET_BUN';
export const SET_FILLING = 'SET_MAIN_INGREDIENT';
export const REMOVE_FILLING_ELEMENT = 'REMOVE_MAIN_INGREDIENT';